version: '3.9'

services:
  api:
    build: .
    container_name: otp-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: otp
      POSTGRES_PASSWORD: otp123
      POSTGRES_DB: otpdb
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"